---
- name: Correction CIS basique Windows
  hosts: windows
  gather_facts: no
  collections:
    - ansible.windows

  tasks:
    - name: Activer la journalisation des événements de sécurité (audit des connexions réussies)
      ansible.windows.win_audit_policy_system:
        category: Logon/Logoff
        subcategory: Logon
        audit_type: Success,Failure

    - name: Désactiver le partage SMBv1 (CIS recommande de le désactiver)
      ansible.windows.win_feature:
        name: FS-SMB1
        state: absent
        restart: no

    - name: Configurer le délai d’expiration du verrouillage de session à 15 minutes
      ansible.windows.win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
        name: InactivityTimeoutSecs
        datatype: dword
        data: 900

    - name: Assurer que le pare-feu Windows est activé (profil Domaine)
      ansible.windows.win_firewall_profile:
        profile: Domain
        state: enabled

    - name: Assurer que le pare-feu Windows est activé (profil Privé)
      ansible.windows.win_firewall_profile:
        profile: Private
        state: enabled

