---
- name: Correction CIS basique Windows
  hosts: windows
  gather_facts: no
  collections:
    - ansible.windows

  tasks:
    - name: Activer la journalisation des événements de sécurité (audit de la sous-catégorie Logon)
      ansible.windows.win_audit_policy_system:
        subcategory: Logon
        audit_type: Success,Failure

    - name: Désactiver le partage SMBv1 (CIS recommande de le désactiver)
      ansible.windows.win_feature:
        name: FS-SMB1
        state: absent
        restart: no

    - name: Configurer le délai d’expiration du verrouillage de session à 15 minutes
      ansible.windows.win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
        name: InactivityTimeoutSecs
        datatype: dword
        data: 900

    - name: Installer les mises à jour Windows critiques et de sécurité
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes

    

